### ISSUE TITLE
Publish newest version

### ISSUE THREAD

**Issue by don41382** [seblm/sbt-jgiven-scalatest-reporter#4]
Hi Sebastian,

Thanks for the nice reporter. Is the version 0.4-SNAPSHOT already on maven?  Or is there an alternative way to get this version working in my SBT project?

Thanks for your help.

Cheers,
Felix

**Comment by seblm** [comment]
Hi Felix,

I am glad you like it.

I will try to release 0.4 this evening🤞. I have already tried to publish 0.2 and 0.3 but encounter some issue during the process.

**Comment by seblm** [comment]
I have published 0.4 to sonatype. Everything is fine except package is not yet available from maven central. I hope synchronization will occur in a few hours.

**Comment by seblm** [comment]
@don41382 you can get the reporter 0.4: I have released it on maven central (https://search.maven.org/artifact/io.github.seblm/sbt-json-scalatest-reporter/0.4)

**Comment by don41382** [comment]
Yes, it's there! Thanks for the super quick response! Appreciate it!
